In [3]:
import numpy as np

## Ôn tập RNN

In [4]:
def cell(input_x, hidden_state):
  return np.tanh(input_x * U + hidden_state * W) * V

In [5]:
X = np.array([0.3, 0.1, 0.55, 0.2, 0.7])
U = 0.75
W = 0.1
V = 0.5
h = 0

for index, input_t in enumerate(X):
  prevous_h = h
  h = output_t = cell(input_t, h)
  print("{}, Input: {:.2f}, Hidden state: {:.2f}, Output: {:.2f}".format(index, input_t, output_t, prevous_h))

0, Input: 0.30, Hidden state: 0.11, Output: 0.00
1, Input: 0.10, Hidden state: 0.04, Output: 0.11
2, Input: 0.55, Hidden state: 0.20, Output: 0.04
3, Input: 0.20, Hidden state: 0.08, Output: 0.20
4, Input: 0.70, Hidden state: 0.24, Output: 0.08


## LSTM

### Hadamard (Multiply Element-wise) product vs Dot product

In [6]:
a = np.array([[1,2], [3,4]])
b = np.array([[0.1,0.9], [0.7,0.3]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[0.1 0.9]
 [0.7 0.3]]


In [7]:
print("Hadamard product: \n{}\n".format(np.multiply(a, b)))
print("Dot product: \n{}".format(np.dot(a, b)))

Hadamard product: 
[[0.1 1.8]
 [2.1 1.2]]

Dot product: 
[[1.5 1.5]
 [3.1 3.9]]


### LSTM

In [8]:
x_1 = np.array([[2, 3, -1]])
Wf = np.array([[1, -2, 5], [5,5,0]])
Uf = np.array([[1,5],[2,1]])
Wi = np.array([[0, 2, 5], [3, -4, 1]])
Ui = np.array([[-1, -5], [2, 1]])
Wo = np.array([[1, 2, 1], [0, -1, 3]])
Uo = np.array([[2, 4], [0, 3]])
Wc = np.array([[-2, 0, 1], [5, 1, 8]])
Uc = np.array([[1, -1], [0, -2]])
bi = bo = bf = bc = np.array([[5, 2]])

In [9]:
def sigmoid(x):
  return 1 / (1 + np.exp(x))

def ft(x_t, h_p_t):
  return sigmoid(Wf.dot(x_t.T) + Uf.dot(h_p_t.T) + bf.T).squeeze()

def it(x_t, h_p_t):
  return sigmoid(Wi.dot(x_t.T) + Ui.dot(h_p_t.T) + bi.T).squeeze()

def ot(x_t, h_p_t):
  return sigmoid(Wo.dot(x_t.T) + Uo.dot(h_p_t.T) + bo.T).squeeze()

def C_hat_t(x_t, h_p_t):
  return np.tanh(Wc.dot(x_t.T) + Uc.dot(h_p_t.T) + bc.T).squeeze()

In [10]:
h_0 = np.array([[0, 0]])
c_0 = np.array([[0, 0]])
f_1 = ft(x_1, h_0)
i_1 = it(x_1, h_0)
o_1 = ot(x_1, h_0)

print("f_1: \n{}\n".format(f_1.shape))
print("i_1: \n{}\n".format(i_1))
print("o_1: \n{}\n".format(o_1))

f_1: 
(2,)

i_1: 
[0.00247262 0.99330715]

o_1: 
[6.1441746e-06 9.8201379e-01]



In [11]:
C_hat_1 = C_hat_t(x_1, h_0)
C_1 = np.multiply(f_1, c_0.squeeze()) + np.multiply(i_1, C_hat_1)
h_1 = np.multiply(o_1, np.tanh(C_1))
print("C_hat_1: \n{}\n".format(C_hat_1))
print("C_1: \n{}\n".format(C_1))
print("h_1: \n{}\n".format(h_1))

C_hat_1: 
[0.         0.99999834]

C_1: 
[0.        0.9933055]

h_1: 
[0.         0.74512091]

